import type { Metadata } from "next";
import { Montserrat, Quicksand } from "next/font/google";
import "@/Core/styles/main.scss";
import Header from "@/Core/components/Header";
import styles from "./styles.module.scss";
import Footer from "@/Core/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className={styles.page}>
          <Header />
          <div className={styles.content}>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
