import { Project } from "../types/Project";

export const Projects: Project[] = [
  {
    name: "BERJER KOLEKSİYONU",
    slug: "berjer-koleksiyonu",
    year: 2025,
    service: "Mobilya Tasarımı",
    type: "Özel Ölçü & Detaylı İşçilik",
    location: "İstanbul",
    images: ["/projects/berjer/1.jpg"],
  },
  {
    name: "ÇALIŞMA ODASI",
    slug: "calisma-odasi",
    year: 2025,
    service: "İç Mimari & Uygulama Projesi",
    type: "Özel Üretim Salon Tezgahları",
    location: "İstanbul",
    images: [
      "/projects/calismaodasi/1.jpg",
      "/projects/calismaodasi/2.jpg",
      "/projects/calismaodasi/3.jpg",
    ],
  },
  {
    name: "KUAFÖR",
    slug: "kuafor-tezgahlari",
    year: 2024,
    service: "Mobilya & İç Mimari Tasarım",
    type: "Özel Üretim Salon Tezgahları",
    location: "İstanbul",
    images: [
      "/projects/kuafor/1.jpg",
      "/projects/kuafor/2.jpg",
      "/projects/kuafor/3.jpg",
      "/projects/kuafor/4.jpg",
      "/projects/kuafor/5.jpg",
      "/projects/kuafor/6.jpg",
      "/projects/kuafor/7.jpg",
      "/projects/kuafor/8.jpg",
      "/projects/kuafor/9.jpg",
      "/projects/kuafor/10.jpg",
      "/projects/kuafor/11.jpg",
      "/projects/kuafor/12.jpg",
      "/projects/kuafor/13.jpg",
      "/projects/kuafor/14.jpg",
      "/projects/kuafor/15.jpg",
      "/projects/kuafor/16.jpg",
      "/projects/kuafor/17.jpg",
      "/projects/kuafor/18.jpg",
      "/projects/kuafor/19.jpg",
      "/projects/kuafor/20.jpg",
      "/projects/kuafor/21.jpg",
      "/projects/kuafor/22.jpg",
    ],
  },
  {
    name: "MUTFAK",
    slug: "mutfak",
    year: 2024,
    service: "Mobilya & İç Mimari Tasarım",
    type: "Özel Üretim Salon Tezgahları",
    location: "İstanbul",
    images: [
      "/projects/mutfak/1.jpg",
      "/projects/mutfak/2.jpg",
      "/projects/mutfak/3.jpg",
      "/projects/mutfak/4.jpg",
      "/projects/mutfak/5.jpg",
      "/projects/mutfak/6.jpg",
      "/projects/mutfak/7.jpg",
      "/projects/mutfak/video.mp4",
    ],
  },
];
